include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    # Enable core Flutter lint rules
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    # Disable problematic rules
    no_wildcard_variable_uses: false
    type_literal_in_constant_pattern: false